steps:
  - name: 'mcr.microsoft.com/dotnet/core/sdk:6.x'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd Trainmate/Trainmate.Api  # Ajusta esto a la ruta correcta
        dotnet restore
        dotnet build
        dotnet publish -c Release -o out

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'app'
      - 'deploy'
      - 'app.yaml'
      - '--version'
      - '$COMMIT_SHA'

substitutions:
  _DOTNET_VERSION: '6.x'
  COMMIT_SHA: '$SHORT_SHA'
