name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v7
      with:
        dotnet-version: 6.0.22  # Reemplaza esto con tu versión exacta de .NET 6.0

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish
      run: dotnet publish --configuration Release --output publish/

  deploy:
    runs-on: ubuntu-latest

    needs: build  # Asegúrate de que la tarea de construcción se haya completado antes de desplegar

    steps:
    - name: Deploy to Production
      run: |
        # Aquí colocarías los comandos específicos para tu despliegue
        # Por ejemplo, podrías copiar los archivos publicados a tu servidor
        # o usar herramientas específicas de despliegue

