name: dotnet package

on: 
  push:
    branches:
      - 'feature/connection_repositorie'

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        dotnet-version: ['6.0.x']

    steps:
      # ... (otros pasos)

      - name: Display dotnet version
        run: |
          dotnet_version=$(dotnet --version)
          echo "dotnet version is $dotnet_version"
          echo "dotnet_version=$dotnet_version" >> $GITHUB_ENV

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Obtener URL de Despliegue
        run: |
          # Accede a la variable de entorno que contiene la versión de .NET
          echo "La versión de dotnet es: $dotnet_version"
          # Agrega aquí los comandos para desplegar tu proyecto y obtener la URL de despliegue
          # Por ejemplo, si estás utilizando GitHub Pages
          $deployUrl = "https://$env:GITHUB_ACTOR.github.io/$env:GITHUB_REPOSITORY"
          echo "La URL de despliegue es: $deployUrl"
