name: dotnet package

on: [push]

jobs:
  build:
    runs-on: self-hosted  # Cambia 'ubuntu-latest' a 'self-hosted'
    strategy:
      matrix:
        dotnet-version: ['6.0.x']

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      # Puedes probar tu matriz imprimiendo la versión actual de dotnet
      - name: Display dotnet version
        run: dotnet --version

