name: dotnet package

on: [push]

jobs:
  build:
  
    runs-on: self-hosted
    strategy:
      matrix:
        dotnet-version: ['6.0.x']

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      # You can test your matrix by printing the current dotnet version
      - name: Display dotnet version
        run: dotnet --version

        
      # Aquí van tus pasos de construcción y compilación

      - name: Obtener URL de Despliegue
        run: |
          # Agrega aquí los comandos para desplegar tu proyecto y obtener la URL de despliegue
          # Por ejemplo, si estás utilizando GitHub Pages
          DEPLOY_URL="https://$GITHUB_ACTOR.github.io/$GITHUB_REPOSITORY"
          echo "La URL de despliegue es: $DEPLOY_URL"

      # Puedes probar tu matriz imprimiendo la versión actual de dotnet
      - name: Display dotnet version
        run: dotnet --version
